apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: app-workloads
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app-workloads
  name: deployer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: app-workloads
subjects:
  - kind: ServiceAccount
    name: deployer-sa
    namespace: app-workloads
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io