apiVersion: v1
kind: Pod
metadata:
  name: privileged-test
  namespace: app-workloads
spec:
  containers:
    - name: privileged-test
      image: nginx
      securityContext:
        privileged: true